import os
import random
import requests
import time
from datetime import datetime
from dotenv import load_dotenv
from utils import save_json, log_campaign
from log import get_logger

API_DELAY = 0.5  # 0.5 seconds between API calls
# Get logger for API client messages
logger = get_logger()

# Import from config files
from config import (
    PERSONAS,
    get_persona_value,
    get_persona_name,
    get_persona_keys,
    DEMO_CONTACTS,
    EMAIL_TO_PERSONA,
    get_demo_contacts_by_persona
)

load_dotenv()

# Headers for API calls
HEADERS = {
    "Authorization": f"Bearer {os.getenv('HUBSPOT_ACCESS_TOKEN')}",
    "Content-Type": "application/json"
}

# ============================================
# CONTACT CREATION WITH PERSONA
# ============================================

def create_contact_with_persona(contact_info):
    #Create a new contact in HubSpot WITH persona assigned at creation time
    time.sleep(API_DELAY)  # Add delay to avoid rate limiting
    try:
        url = "https://api.hubapi.com/crm/v3/objects/contacts"
        
        properties = {
            "email": contact_info['email'],
            "firstname": contact_info['firstname'],
            "lastname": contact_info['lastname'],
            "hs_persona": contact_info['persona']
        }
        
        payload = {"properties": properties}
        
        response = requests.post(url, json=payload, headers=HEADERS)
        
        if response.status_code in [200, 201]:
            contact_id = response.json().get('id')
            persona_name = get_persona_name(contact_info['persona'])
            logger.info(f"Created: {contact_info['firstname']} {contact_info['lastname']} (Persona: {persona_name})")
            return contact_id
        else:
            logger.info(f"Failed: {contact_info['email']} - HTTP {response.status_code}")
            return None
            
    except Exception as e:
        logger.info(f"Error: {e}")
        return None

# ============================================
# CAMPAIGN LOGGING TO CONTACT NOTES
# ============================================

def add_campaign_note_to_contact(contact_id, blog_title, campaign_id, persona, send_date, newsletter_id, newsletter_preview=""):
    """
    Add a note to a specific contact's timeline in HubSpot
    Uses associations to link the note to the contact
    """
    try:
        url = "https://api.hubapi.com/crm/v3/objects/notes"
        
        # Convert send_date to milliseconds timestamp
        from datetime import datetime
        if isinstance(send_date, str):
            if 'T' in send_date:
                dt = datetime.fromisoformat(send_date.replace('Z', '+00:00'))
            else:
                dt = datetime.now()
        else:
            dt = send_date
        
        timestamp_ms = int(dt.timestamp() * 1000)
        
        # Format the note body with proper line breaks
        note_body = f"""CAMPAIGN RECEIVED<br>
            Date: {dt.strftime('%Y-%m-%d %H:%M:%S')}<br>
            Blog Title: {blog_title}<br>
            Campaign ID: {campaign_id}<br>
            Newsletter ID: {newsletter_id}<br>
            Persona Segment: {persona}<br>
            Generated by NovaMind AI Marketing Pipeline"""
        
        # Build payload with associations
        payload = {
            "properties": {
                "hs_timestamp": timestamp_ms,
                "hs_note_body": note_body
            },
            "associations": [
                {
                    "to": {
                        "id": str(contact_id)
                    },
                    "types": [
                        {
                            "associationCategory": "HUBSPOT_DEFINED",
                            "associationTypeId": 202
                        }
                    ]
                }
            ]
        }
        
        response = requests.post(url, json=payload, headers=HEADERS)
        
        if response.status_code in [200, 201]:
            note_id = response.json().get('id')
            return True, note_id
        else:
            logger.info(f"Failed to add note: HTTP {response.status_code}")
            return False, None
            
    except Exception as e:
        logger.info(f"Error adding note: {e}")
        return False, None


def log_campaign_to_all_contacts(contact_ids, blog_title, campaign_id, persona, send_date, newsletter_id, newsletter_content=""):
    """
    Log campaign to every contact in the contact list
    Creates a note linked to each contact's timeline
    """
    if not contact_ids:
        return 0
    
    success_count = 0
    
    for contact_id in contact_ids:
        if isinstance(contact_id, str) and contact_id.startswith('mock'):
            continue
        
        contact_id_str = str(contact_id)
        
        success, _ = add_campaign_note_to_contact(
            contact_id=contact_id_str,
            blog_title=blog_title,
            campaign_id=campaign_id,
            persona=persona,
            send_date=send_date,
            newsletter_id=newsletter_id,
            newsletter_preview=newsletter_content[:300] if newsletter_content else ""
        )
        
        if success:
            success_count += 1
    
    if success_count > 0:
        logger.info(f"Added campaign notes to {success_count} contact(s) in HubSpot")
    
    return success_count

# ============================================
# CONTACT MANAGEMENT
# ============================================

def get_all_contacts(limit=100):
    #Get all contacts from HubSpot including hs_persona
    try:
        url = f"https://api.hubapi.com/crm/v3/objects/contacts?limit={min(limit, 100)}&properties=email,firstname,lastname,hs_persona"
        
        response = requests.get(url, headers=HEADERS)
        
        if response.status_code == 200:
            data = response.json()
            contacts = []
            
            for result in data.get('results', []):
                props = result.get('properties', {})
                persona_value = props.get('hs_persona')
                
                # Find persona name using config
                persona_name = "Not Set"
                for p_key, p_config in PERSONAS.items():
                    if p_config['value'] == persona_value:
                        persona_name = p_config['name']
                        break
                
                contacts.append({
                    'id': result.get('id'),
                    'email': props.get('email'),
                    'firstname': props.get('firstname', ''),
                    'lastname': props.get('lastname', ''),
                    'persona_value': persona_value,
                    'persona_name': persona_name,
                    'has_persona': persona_value is not None and persona_value != ""
                })
            
            logger.info(f"Fetched {len(contacts)} contacts")
            return contacts
        else:
            return []
            
    except Exception as e:
        logger.info(f"Error: {e}")
        return []

def ensure_contacts_exist():
    #Create demo contacts if they don't exist
    logger.info("\n" + "="*70)
    logger.info("CREATING DEMO CONTACTS WITH PERSONAS")
    logger.info("="*70)
    
    existing_contacts = get_all_contacts(limit=100)
    existing_emails = set(c.get('email') for c in existing_contacts if c.get('email'))
    
    created_count = 0
    
    for contact in DEMO_CONTACTS:
        if contact['email'] not in existing_emails:
            contact_id = create_contact_with_persona(contact)
            if contact_id:
                created_count += 1
        else:
            logger.info(f"Already exists: {contact['email']}")
    
    if created_count > 0:
        logger.info(f"\nCreated {created_count} new contacts")
    else:
        logger.info(f"\nAll demo contacts already exist")
    
    return created_count

def print_contact_summary():
    #Print summary of all contacts with their personas
    contacts = get_all_contacts(limit=50)
    
    logger.info("\n" + "="*70)
    logger.info("CONTACTS IN HUBSPOT")
    logger.info("="*70)
    
    if not contacts:
        logger.info("   No contacts found")
        return
    
    logger.info(f"\n{'Name':<25} {'Email':<30} {'Persona':<20}")
    logger.info("-" * 75)
    
    for contact in contacts:
        name = f"{contact.get('firstname', '')} {contact.get('lastname', '')}".strip() or "Unknown"
        email = contact.get('email', 'No email')[:28]
        
        if contact.get('has_persona'):
            persona_display = f"{contact.get('persona_name', '')}"
        else:
            persona_display = "Not Set"
        
        logger.info(f"{name:<25} {email:<30} {persona_display:<20}")
    
    with_persona = sum(1 for c in contacts if c.get('has_persona'))
    without_persona = len(contacts) - with_persona
    
    logger.info("\n" + "-" * 75)
    logger.info(f"Summary: {with_persona} have personas, {without_persona} need assignment")

def get_persona_distribution():
    #Get distribution of personas
    distribution = {persona: 0 for persona in get_persona_keys()}
    distribution['unassigned'] = 0
    
    contacts = get_all_contacts(limit=200)
    
    for contact in contacts:
        if contact.get('has_persona'):
            persona_value = contact.get('persona_value')
            for p_key in get_persona_keys():
                if PERSONAS[p_key]['value'] == persona_value:
                    distribution[p_key] += 1
                    break
        else:
            distribution['unassigned'] += 1
    
    return distribution

# ============================================
# MAIN SYNC FUNCTION
# ============================================

def sync_contacts_and_campaign(blog_title, newsletters):
    """
    Main sync function:
    1. Create contacts with personas
    2. Segment by persona
    3. Log campaign to JSON file
    4. Log campaign to each contact's note in HubSpot
    """
    campaign_results = {}
    
    if not os.getenv('HUBSPOT_ACCESS_TOKEN'):
        logger.info("\nNo HubSpot token. Using mock mode.")
        return mock_sync(blog_title, newsletters)
    
    # Create contacts with personas
    ensure_contacts_exist()
    
    # Show all contacts
    print_contact_summary()
    
    # Show persona distribution
    logger.info("\n" + "="*70)
    logger.info("PERSONA DISTRIBUTION")
    logger.info("="*70)
    
    distribution = get_persona_distribution()
    for persona_key in get_persona_keys():
        logger.info(f"{PERSONAS[persona_key]['name']}: {distribution.get(persona_key, 0)} contacts")
    logger.info(f"Unassigned: {distribution.get('unassigned', 0)} contacts")
    
    # Get all contacts for segmentation
    all_contacts = get_all_contacts(limit=200)
    
    # Prepare campaigns by persona
    logger.info("\n" + "="*70)
    logger.info("PREPARING PERSONA-SPECIFIC CAMPAIGNS")
    logger.info("="*70)
    
    send_date = datetime.now().isoformat()
    
    for persona_key in get_persona_keys():
        persona_config = PERSONAS[persona_key]
        logger.info(f"\n   {persona_config['name']}:")
        
        # Get contacts with this persona
        persona_contacts = [c for c in all_contacts if c.get('persona_value') == persona_config['value']]
        contact_ids = [c['id'] for c in persona_contacts]
        
        # Create campaign ID and newsletter ID
        campaign_id = f"campaign_{blog_title[:20].replace(' ', '_')}_{persona_key}_{random.randint(1000,9999)}"
        newsletter_id = f"newsletter_{persona_key}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        if contact_ids:
            logger.info(f"Found {len(contact_ids)} contacts with this persona")
            for contact in persona_contacts[:3]:
                name = f"{contact.get('firstname', 'Unknown')}"
                logger.info(f"{name} ({contact.get('email')})")
        else:
            logger.info(f"No contacts with this persona yet")
        
        # STEP 1: Log to JSON file (backup)
        log_campaign(
            blog_title=blog_title,
            persona=persona_key,
            campaign_id=campaign_id,
            contact_ids=contact_ids,
            log_file='campaign_log.json'
        )
        
        # STEP 2: Log to each contact's timeline in HubSpot
        newsletter_content = newsletters.get(persona_key, "")
        note_count = log_campaign_to_all_contacts(
            contact_ids=contact_ids,
            blog_title=blog_title,
            campaign_id=campaign_id,
            persona=persona_config['name'],
            send_date=send_date,
            newsletter_id=newsletter_id,
            newsletter_content=newsletter_content
        )
        
        campaign_results[persona_key] = {
            'campaign_id': campaign_id,
            'newsletter_id': newsletter_id,
            'contact_ids': contact_ids,
            'contact_count': len(contact_ids),
            'notes_added': note_count,
            'send_date': send_date,
            'blog_title': blog_title
        }
        
        logger.info(f"Campaign logged: {campaign_id}")
        logger.info(f"Newsletter ID: {newsletter_id}")
        logger.info(f"Send Date: {send_date[:19]}")
        logger.info(f"Contacts: {len(contact_ids)}")
    
    save_json(campaign_results, 'latest_campaign.json')
    return campaign_results

def mock_sync(blog_title, newsletters):
    #Mock mode fallback
    logger.info("\nMOCK MODE")
    campaign_results = {}
    
    send_date = datetime.now().isoformat()
    
    for persona_key in get_persona_keys():
        mock_contact_ids = [f"mock_{i}" for i in range(1, 4)]
        campaign_id = f"campaign_mock_{persona_key}_{random.randint(1000,9999)}"
        
        log_campaign(blog_title, persona_key, campaign_id, mock_contact_ids, log_file='campaign_log.json')
        
        campaign_results[persona_key] = {
            'campaign_id': campaign_id,
            'contact_ids': mock_contact_ids,
            'contact_count': len(mock_contact_ids),
            'send_date': send_date,
            'blog_title': blog_title
        }
        
        print(f"Mock: {len(mock_contact_ids)} {PERSONAS[persona_key]['name']} contacts")
    
    save_json(campaign_results, 'latest_campaign.json')
    return campaign_results

if __name__ == "__main__":
    test_newsletters = {
        'creative_director': 'Test for creative directors',
        'automation_specialist': 'Test for automation specialists',
        'freelance_designer': 'Test for freelancers'
    }
    sync_contacts_and_campaign("Test AI Campaign", test_newsletters)
